### ISSUE TITLE
AutoCaptcha contribution

### ISSUE THREAD

**Issue by karthikb351** [rahulkapoor90/StudentLogin-VIT#1]
This could go into the AutoCaptcha extension. perfect way to package and distribute it.

**Comment by rahulkapoor90** [comment]
Sure, why not!

**Comment by karthikb351** [comment]
You just need to add it to the manifest, and declare what CSS you want loaded on what page.

See this - https://github.com/karthikb351/AutoCaptcha-for-Chrome/blob/master/autocaptcha-for-chrome/manifest.json

**Comment by rahulkapoor90** [comment]
Like this?

"content_scripts": [
   {
      "matches":    ["http://www.academics.vit.ac.in/*"],
      "css":        ["stusentlogin.css"]
   }
],

**Comment by rahulkapoor90** [comment]
Done.
